class RootException(Exception):
    pass


class CollectorError(RootException):
    pass
